easy_email.easy_email_type.*:
  type: config_entity
  label: 'Email template config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    key:
      type: string
    recipient:
      type: sequence
      label: 'Recipients'
      orderby: key
      sequence:
        type: string
        label: 'Recipient'
        translatable: true
    cc:
      type: sequence
      label: 'CC'
      orderby: key
      sequence:
        type: string
        label: 'CC Recipient'
        translatable: true
    bcc:
      type: sequence
      label: 'BCC'
      orderby: key
      sequence:
        type: string
        label: 'BCC Recipient'
        translatable: true
    fromName:
      type: text
      label: 'From Name'
    fromAddress:
      type: string
      label: 'From Address'
      translatable: true
    replyToAddress:
      type: string
      label: 'Reply To Address'
      translatable: true
    subject:
      type: text
      label: 'Subject'
    inboxPreview:
      type: text
      label: 'Inbox Preview'
    bodyHtml:
      type: mapping
      label: 'HTML Body'
      mapping:
        value:
          type: text
          label: 'Text Value'
        format:
          type: string
          label: 'Text Format'
    bodyPlain:
      type: text
      label: 'Plain Text Body'
    generateBodyPlain:
      type: boolean
      label: 'Generate Plain Text Body from HTML Body'
    attachment:
      type: sequence
      label: 'Attachments'
      orderby: key
      sequence:
        type: string
        label: 'Attachment'
    saveAttachment:
      type: boolean
      label: 'Save Attachments'
    attachmentScheme:
      type: string
      label: 'Attachment URI Scheme'
    attachmentDirectory:
      type: string
      label: 'Attachment Directory'
    saveEmail:
      type: boolean
      label: 'Save Emails by Default'
    allowSavingEmail:
      type: boolean
      label: 'Allow Emails to be Saved'
    purgeEmails:
      type: boolean
      label: 'Purge Emails'
    purgeInterval:
      type: integer
      label: 'Purge Interval'
    purgePeriod:
      type: string
      label: 'Purge Period'
